spring:
  application:
    name: SpringSecurityJWT
  datasource:
    url: jdbc:postgresql://localhost:5432/springsecurity
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: TRACE
